package com.wbandara.enterprise.runners;

import io.cucumber.testng.AbstractTestNGCucumberTests;
import io.cucumber.testng.CucumberOptions;
import org.testng.annotations.DataProvider;

/**
 * Runner for failed scenarios (rerun).
 * Reads failed scenarios from the rerun file generated by previous test run.
 */
@CucumberOptions(
        features = "@target/failed_scenarios.txt",
        glue = {
                "com.wbandara.enterprise.stepdefinitions",
                "com.wbandara.enterprise.hooks"
        },
        plugin = {
                "pretty",
                "html:target/cucumber-reports/rerun-cucumber.html",
                "json:target/cucumber-reports/rerun-cucumber.json",
                "io.qameta.allure.cucumber7jvm.AllureCucumber7Jvm"
        },
        monochrome = true
)
public class FailedTestRunner extends AbstractTestNGCucumberTests {

    @Override
    @DataProvider(parallel = false)
    public Object[][] scenarios() {
        return super.scenarios();
    }
}

